### PR TITLE
Fix incorrect variadic arg wrangling in get_services

### LINKED ISSUE #694: Harness.Container.get_services() does not seem correctly mocked
I think this test should work, but it does not with `ops 1.3.0`:

```
    def test_mocked_get_services(self):
        self.harness.begin()
        traefik_container = self.harness.charm.unit.get_container("traefik")
        traefik_container.add_layer("traefik_layer", {
            "summary": "Traefik layer",
            "description": "Pebble config layer for Traefik",
            "services": {
                "traefik": {
                    "override": "replace",
                    "summary": "Traefik",
                    "command": "/usr/bin/traefik",
                },
            },
        })

        assert traefik_container.get_service("traefik")  # So far, so good
        assert "traefik" in traefik_container.get_services()  # FAILS, `traefik_container.get_services()` returns {} 
```

### PR DESCRIPTION
**Pull request by rwcarlsen**
Fixes #694

### CODE REVIEW

**Comment by rwcarlsen** [comment]
The other option is to go into the pebble regular and test clients and make them treat an empty list the same as a None arg.  Not sure which approach is better.  Opinions welcome.

**Comment by benhoyt** [comment]
Note that the `canonical/grafana-operator` tests are failing due to https://github.com/canonical/grafana-k8s-operator/pull/68. I've hacked around that in https://github.com/canonical/operator/pull/668/files#diff-d899f68301edb06393d5435313801f676fc892f1484aa76f10d82c36e5e022f2R26

**Review by benhoyt — APPROVED** [review]
Seems reasonable to me, thanks!

**Review by jnsgruk — APPROVED** [review]
LGTM

**Pull request merged**
