### PR TITLE
Add Leadership Settings

### PR DESCRIPTION
**Pull request by stub42**
Add the backend stuff for leader-set and leader-get Juju hook tools. ~They are not (yet) exposed at a higher level.~ And an API for charms to access the leadership settings as a mapping.

### CODE REVIEW

**Comment by stub42** [comment]
I went with `leadership_settings` (as in `self.model.leadership_settings['foo'] = 'bar'), because that is how the leader-get and leader-set tools reference this data bag. Alternatives would be leader_settings, leadership_data or leader_data.

**Comment by petevg** [comment]
This PR has been hanging out for a while. @jnsgruk do we have any specific plans (or lack of plans) around this? If not, this PR looks sensible to me, and I think that we could merge it.

**Comment by jnsgruk** [comment]
AIUI, we're encouraging people to use peer relations to achieve this functionality now, and probably don't want to merge this PR.

Peer relations do in fact provide the same functionality here, in that only the leader can set *application data* on the peer relation, and units can set their own *unit data*. Encouraging charmers down this route also means there are shared semantics/concepts between handling data on relations between units, and interacting with other applications over provides/requires relations.

My view is that we should probably close this without merging, though I'm open to input from @jameinel and @niemeyer in case I've missed anything.

**Comment by jameinel** [comment]
Just to proxy for Stub who is no longer here, the reason he wanted leader
functionality is  because he knew it would always be present without
further introspection/communication. (Eg a client of postgresql could use
local leader data without requiring the charm to implement a peer relation
and inform the psql client the name of that relation.)

There is some value in that, but it complicates the number of possible ways
that you can collaborate as a charm, and removing leader-set/leader-get and
not having to implement the associated 'leader-settings-changed' seems a
net win for charmers, as they have fewer things to take into consideration.
But it does mean that a psql client library that communicates about the
psql relation would also want to know about a peer relation informed to
them by the charm.

It is a pattern that we would like to establish in a nice way for charmers,
but I think we want to do it via peer relation vs leader-set/get. If it
leads to hard-to-maintain/poor charms, then we should reconsider.

**Comment by petevg** [comment]
Per the discussion above, I am going to close this PR.

**Pull request closed without merging**
