### PR TITLE
Create stale.yml

### PR DESCRIPTION
**Pull request by petevg**
This was recommended to me by github, and I like it. Goes and cleans up old and stale issues. (We can re-open if we disagree, of course.)

### CODE REVIEW

**Comment by jtroup** [comment]
I don't have an actual vote, obviously, but please don't do this.  Automatically closing issues just because they haven't had an update in a while is one of the most frustratingly user-hostile things that developers do.  It actively discourages users and community and for (IMO) very little actual benefit.

**Comment by benhoyt** [comment]
I agree with @jtroup. The actual issues (probably) haven't gone away. Manually going through old issues and evaluating them is a much better way, though obviously more time-consuming. We can always think about it and respond Won'tFix for such-and-such a reason, but just closing after N days seems wrong.

**Comment by petevg** [comment]
> I don't have an actual vote, obviously, but please don't do this. Automatically closing issues just because they haven't had an update in a while is one of the most frustratingly user-hostile things that developers do. It actively discourages users and community and for (IMO) very little actual benefit.

I hear you, and I definitely do not want to create an environment that is hostile to feedback, in fact or in impression.

I do want to avoid a situation where we have a lot of open issues, some of which have a low probability of being worked on, and it becomes difficult to find active issues, or get a sense for where the project is headed, and which issues are going to be worked on.

I will give some thought to simply going through the issues by hand, and closing the ones that seem like they aren't relevant to the framework at present. That does risk making the issue closing feel more personal, but I am generally comfortable being the bad guy/girl. :-) 

Fundamentally, I don't want to create a situation where the issue backlog starts to get ignored, because it is too time consuming for anyone, devs or community members, to go through and figure out what the current and relevant issues are. I'm not attached to this particular solution.

**Comment by benhoyt** [comment]
Actually, I would be okay with this with a modification: if we've asked for more information/clarification *and* no one has responded for (say) 60 days, mark as stale and then close after 7 days. This would mean clear issues aren't just closed, but issues where the reporter doesn't get back to us with clarifying info will be closed. I *think* you could do this with a new `info-needed` label and the actions/stale bot `exempt-*` settings. I believe this is basically what we do on Juju (Launchpad issues). Thoughts @jtroup?

**Comment by jtroup** [comment]
> Actually, I would be okay with this with a modification: if we've asked for more information/clarification _and_ no one has responded for (say) 60 days, mark as stale and then close after 7 days. This would mean clear issues aren't just closed, but issues where the reporter doesn't get back to us with clarifying info will be closed. I _think_ you could do this with a new `info-needed` label and the actions/stale bot `exempt-*` settings. I believe this is basically what we do on Juju (Launchpad issues). Thoughts @jtroup?

No objections to that from me.

**Comment by jnsgruk** [comment]
Hi all,

I think at the moment we have a pretty manageable level of issue creation etc. While we firm up our process, and as the project grows, I think we should exercise a bit more caution. Once we have an established pattern, and activity has picked up again I think we could consider implementing something like this.

Closing for now, but I could see this reopening in the future.

**Pull request closed without merging**
