### PR TITLE
chore: standardise copyright headers

### LINKED ISSUE #1325: Remove copyright years from source files
Per team discussion, we're going to remove the copyright year (or year range in some cases) from the top of each source file, but leave the copyright notice itself, so the first line just says `# Copyright Canonical Ltd.`.

[This blog post](https://hynek.me/til/copyright-years/) notes that various large projects and companies have started doing this ([curl](https://daniel.haxx.se/blog/2023/01/08/copyright-without-years/), [React](https://github.com/facebook/react/pull/13593), [Amazon](https://chatter.quux.world/@mark/109621622761353381)), so there's a good precedent.

As mentioned in the [Curl commit])(https://github.com/curl/curl/commit/2bc1d775f510196154283374284f98d3eae03544), there's no legal need:

> - they are mostly pointless in all major jurisdictions
> - many big corporations and projects already don't use them
> - saves us from pointless churn
> - git keeps history for us

### PR DESCRIPTION
**Pull request by james-garner-canonical**
Copyright notice line only needs file creation year (not range).

Full boilerplate from LICENSE.txt should be used (rather than a one line note to see LICENSE).

Copyright notice process documented in HACKING.md.

Resolves #1325

### CODE REVIEW

**Review by tonyandrewmeyer — APPROVED** [review]
LGTM, thanks!

I wonder if it's worth adding a small note somewhere in HACKING.md explaining what we do, to avoid people adding them back later? What do you think?

**Comment by james-garner-canonical** [comment]
> I wonder if it's worth adding a small note somewhere in HACKING.md explaining what we do, to avoid people adding them back later? What do you think?

Technically the instructions we're currently following are documented in LICENSE.txt, but it might be worth adding a note in HACKING.md saying not to change existing notices and to follow those instructions for new files.

**Comment by james-garner-canonical** [comment]
I've noticed that the yaml files under test/charms/test_main/ don't have copyright notices.

Nor do any of the files under docs/ (conf.py, custom_conf.py, index.rst and requirements.txt) or test/bin/ (bash and bat scripts).

Also project .md files and pyproject.toml, but I don't think those would typically require them.

Should any of these have copyright notices added? I'm thinking at least the .yaml and .py files should have them added.

**Comment by benhoyt** [comment]
> I've noticed that the yaml files under test/charms/test_main/ don't have copyright notices.
> 
> Nor do any of the files under docs/ (conf.py, custom_conf.py, index.rst and requirements.txt) or test/bin/ (bash and bat scripts).
> 
> Also project .md files and pyproject.toml, but I don't think those would typically require them.
> 
> Should any of these have copyright notices added? I'm thinking at least the .yaml and .py files should have them added.

I think let's do the yaml files and the docs/*.py files, but not the Markdown/ReST/txt files/.

**Comment by sed-i** [comment]
Not sure about ruff, but with flake8 we could have a regex for the copyright
https://github.com/canonical/operator/blob/7a5513accdd4acf97d929009f8d33be991d9f2b1/pyproject.toml#L95

https://github.com/canonical/alertmanager-k8s-operator/blob/b8d96dd65d83f7af611c23034cc49ed1da4390b6/pyproject.toml#L35

**Comment by tonyandrewmeyer** [comment]
> I think let's do the yaml files and the docs/*.py files, but not the Markdown/ReST/txt files/.

While you're doing this, could you take a little look into why `ruff lint` isn't flagging those doc files? `CPY` is enabled as a check, and at a glance I don't see that disabled for the `docs` folder, and I thought we just recently enabled linting for custom_conf.py.

By the way, for docs/conf.py, I feel like if we add a copyright notice to this it would be better to also submit that upstream, because we're just copying this file into our repo. It's copied from Canonical, so pasting our own copyright on it is probably fine, but really it belongs at the source.

**Comment by benhoyt** [comment]
> By the way, for docs/conf.py, I feel like if we add a copyright notice to this it would be better to also submit that upstream, because we're just copying this file into our repo. It's copied from Canonical, so pasting our own copyright on it is probably fine, but really it belongs at the source.

Oh yes, I'd overlooked that. I think that (at least in this PR) we shouldn't modify anything from upstream, or it'll make updating too messy. Let's just do our files in this PR (custom_config.py?).

**Comment by james-garner-canonical** [comment]
> While you're doing this, could you take a little look into why `ruff lint` isn't flagging those doc files?

There is a global ruff: noqa directive in  both docs/conf.py and docs/custom_conf.py

**Comment by james-garner-canonical** [comment]
> > By the way, for docs/conf.py, I feel like if we add a copyright notice to this it would be better to also submit that upstream, because we're just copying this file into our repo. It's copied from Canonical, so pasting our own copyright on it is probably fine, but really it belongs at the source.
> 
> Oh yes, I'd overlooked that. I think that (at least in this PR) we shouldn't modify anything from upstream, or it'll make updating too messy. Let's just do our files in this PR (custom_config.py?).

I wasn't sure about docs/conf.py due to this. The current version was added without customisation, but was subsequently modified slightly in one commit (noqa added and rst_epilog removed). I won't modify it further in this PR.

**Review by benhoyt — APPROVED** [review]
Looks good to me -- thanks for this!

**Pull request merged**
