### PR TITLE
Update test/lint tooling

### PR DESCRIPTION
**Pull request by jnsgruk**
This PR makes a number of changes to ease working across teams, and increase consistency across the codebase. It also tidies up the root of the repository a little, and consolidates some of tooling/dependency management.

~~This is likely to be a little controversial. While `black` has largely become very common place, it doesn't *always* make the prettiest changes. I've done a first pass over the resulting code and tidied up some of the more egregious instances. My gut feeling is that there is a net win here for consistency throughout the codebase, and the increased automation around linting, formatting, docs building, etc. should make for a smoother development process for most. (Note: a good percentage of the diff is replacing single-quotes with double, so not quite as scary as it looks)~~ Removed `black` for now.

I've done a little consulting around other Python-focused teams in Canonical, and this seems to be the relative norm at this point, and so cross-team contributions could even be a little smoother and more consistent.

Tooling/structural changes:

- Remove `.flake8`, `requirements-dev.txt`, `build_docs`, `run_tests`
- Add `tox.ini` for managing testing/linting environments, and their dependencies
- Add `pyproject.toml` to configure linting and testing tools
- Minor adjustments to tests due to `tox` env differences

Formatting changes:

- Some minor adjustments to docstrings to end with full-stops, remove extra newlines, etc.
- Adjusted README line length to 99 to match the codebase

Other:

- README update to reflect the changes to development process, and some slight terminology/link updates
- Adjustment to CI process so that linting is only run once, not in every version/environment

The 5 commits represent the process I went through to get here pretty cleanly. I'd encourage any reviewers to consider that history if possible.

### CODE REVIEW

**Review by benhoyt — APPROVED** [review]
Thanks, Jon!

The addition of tox looks good, and gets rid of those couple of ad-hoc scripts.

I've used Black at a previous workplace, and while it does take a bit of getting used to, and there are certain things it doesn't do to my taste at all (formatting a dict arg to a function call takes too many lines, and using double quotes :-), it ends all the bike-sheddy discussions about how to format whitespace and multi-line function arguments, and so on. It was a win when using it previously, to avoid those debates, just like `go fmt` does.

P.S. As far as double quotes go, I'd be an advocate of [Blue](https://blue.readthedocs.io/en/latest/), a patch of Black that uses single quotes, which is what the Python oracle says to use:

```
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> "x"
'x'  # Python converting our double quotes to single
```

That said, one does get used to it, and have any auto formatter basically ends trivial style discussions like with `go fmt`. So I'm good with this even if I don't get my single quotes. :-)

**Comment by rbarry82** [comment]
Definitely :+1:  from me. Fighting through what pep8/flake8 _think_ formatting should look like (when parens should be aligned to which column, etc) is always frustrating, no matter how long I've written Python. No more debates. Just write it and let the autoformatter handle the rest.

**Review by rbarry82 — APPROVED** [review]

**Comment by niemeyer** [comment]
We've discussed this to some length privately.  We used _black_ right here on this project as well some time ago, and after several bad experiences that resemble what @benhoyt has described above, we ended up aborting it in favor of autopep8 + flake8, as it exists today already in the tree.

With that said, when @jnsgruk suggested looking into it again, I was happy to do so in the hopes that things had changed. But it doesn't look like the underlying issues that motivated us to drop _black_ before have been fixed, as is observable in the changes in this PR.

Just a few examples:

---

In this case the new logic takes more space, more noisy, yet reads significantly less clearly because the second parameter is hidden at the end of the line, making it look like there's a single parameter, even to a trained eye.

image

---

This one is just awful, and not a matter of opinion in the sense that nobody would ever format code like this.

image

---

Again, this is anti-formatting:

image

---

So, I hate to be that guy again, but we've done this exercise before and reached the same conclusion: _black_ is simply not a good linter or formatting tool for Python. It removes discussions clearly to the detriment of code quality, which is not a great outcome.

With that said, I do agree with the underlying goal of having unnecessary discussions removed, and code formatting being strongly encouraged by a tool. But it's not _black_ or nothing. We do have a code formatting today already, in tree, and the fact that, if I may dare to say, pretty much nothing was improved by this pass of _black_ is because we already have that in place today.

So, if this is an attempt to use _black_ widely for other projects, I'd suggest taking a step back and rethinking and perhaps reusing our prior experience in this project. There are good alternatives that will give you the benefits without the cost.

This is the commit that [removed black originally](0d45b362d34f5223ff5f49169e3aab3bf1a81acc), for reference:

```
commit 0d45b362d34f5223ff5f49169e3aab3bf1a81acc
Author: John Arbash Meinel <john@arbash-meinel.com>
Date:   Wed Nov 27 19:05:35 2019 +0400

    Reformat the code using autopep8 (#58)

    This is a much lighter touch than python-black. It seems to respect the
    existing line lengths, even with --aggressive.
```

**Review by niemeyer — CHANGES_REQUESTED** [review]
Per remarks above.

**Comment by jnsgruk** [comment]
@niemeyer -- black removed for now, can you +1 the tooling and README change?

**Review by benhoyt — APPROVED** [review]

**Comment by Vultaire** [comment]
One bit of feedback I'd give here is that the reformatting in this PR does make it more difficult to pinpoint the key pieces that have changed for the test/lint tooling versus lint/reformatting work.  Generally I'd prefer these types of changes to be distinct.

That aside, generally this looks OK and I'm in favor.

**Pull request merged**
