### PR TITLE
Add info about fixing pyyaml in README.md

### PR DESCRIPTION
**Pull request by dstathis**

### CODE REVIEW

**Comment by jameinel** [comment]
I don't know if that is sufficient. To install pyyaml with extensions also needs your system to have libyaml-dev and Cython available, IIRC.
I'm not sure if it is worth trying to solve in the README, or whether it is better to point people toward a more comprehensive doc (possibly from the warning message itself).

**Comment by chipaca** [comment]
we can instead make the tests resilient to this situation.

**Comment by dstathis** [comment]
> I don't know if that is sufficient. To install pyyaml with extensions also needs your system to have libyaml-dev and Cython available, IIRC.
> I'm not sure if it is worth trying to solve in the README, or whether it is better to point people toward a more comprehensive doc (possibly from the warning message itself).

I don't have cython installed and it worked just fine. I only needed libyaml-dev.

**Comment by dstathis** [comment]
> we can instead make the tests resilient to this situation.

We could certainly do this as the tests are only failing because they are seeing the error message and not because of any functional failure. I would say, though, that it is somewhat useful to get these failures as it tips you off to the fact that you are not properly set up.

**Review by chipaca — APPROVED** [review]
@jameinel this seems to work. We can dig into what needs Cython, and add to these instructions once we've figured that one out.

**Pull request merged**
