### PR TITLE
Add data platform charms to our CI testing

### PR DESCRIPTION
**Pull request by rwcarlsen**
Is this the/an approach (just growing our charm testing list with "stable/good" charms) we want to take to help avoid regressions and breakage downstream when we do releases?  I feel like growing this list (selectively) of charms we test in our CI will be helpful.  But ultimately, for releases, it will probably also be good to test more broadly against other charms to help discover issues.

### CODE REVIEW

**Comment by pengale** [comment]
I am good on this approach. The charms added are maintained by trusted teams, and known to be good quality. 

And we can bug them if they break our CI :-)

**Comment by rwcarlsen** [comment]
I wanted to also include a couple data platform charms.  At the time I started this PR, they didn't have any charms that they felt comfortable committing to the sort of stability we want here.  But I think they might be more ready now.  @delgod - what charms from your team do you think we should add to our CI here?

**Comment by PietroPasotti** [comment]
I think we could also include the charms that we own (traefik, dashboard,...)
if those break the CI, it'd be the ultimate checkmate

**Comment by rwcarlsen** [comment]
So the current CI failures here are from a recent merge where we added extra validation on unit names set by charm devs for harness testing.  So if we put those changes into a release, we'll cause breakage - which are arguably bugs in the charms, but relatively benign ones.  Seems like this is a good case study for the need for these additions to our CI!  So the question is do we roll back the breaking change or do we work to fix the broken charms before merging this?

**Comment by pengale** [comment]
> So the current CI failures here are from a recent merge where we added extra validation on unit names set by charm devs for harness testing. So if we put those changes into a release, we'll cause breakage - which are arguably bugs in the charms, but relatively benign ones. Seems like this is a good case study for the need for these additions to our CI! So the question is do we roll back the breaking change or do we work to fix the broken charms before merging this?

This is a perfect argument for these test being a good idea :-)

I think that we should switch to logging a warning on invalid unit names in tests, rather than raising on error.

We can switch over to errors in some future release.

**Comment by rwcarlsen** [comment]
Okay - I think this should be enough to resolve remaining issues on #776.  The remaining failure here is that the observability folks have `# type: ignore` comments that use to be necessary but are not necessary anymore.  And the way they are running mypy - complains when they have no-longer-needed ignore comments :/  Not sure how to best address that chicken and egg problem.  Ideas welcome.

**Comment by pengale** [comment]
> Okay - I think this should be enough to resolve remaining issues on #776. The remaining failure here is that the observability folks have `# type: ignore` comments that use to be necessary but are not necessary anymore. And the way they are running mypy - complains when they have no-longer-needed ignore comments :/ Not sure how to best address that chicken and egg problem. Ideas welcome.

@simskij it looks like we may need to coordinate with your team on updating your charms with the next release of ops. Do you have any thoughts on the best way to do so?

**Review by pengale — APPROVED** [review]
Since we are down to one known issue, and since this has already caught several errors before they made it into the wild, I am +1 on this change.

**Comment by rwcarlsen** [comment]
Since the fixes caught by this are in #822 - we'll wait for that to be merged first.  Then I'll rebase and we can merge here.

**Comment by rwcarlsen** [comment]
@PietroPasotti - will you push in some traefik charm tests here when you get a chance?  Probably put them in their own workflow file.

**Comment by rwcarlsen** [comment]
ping @PietroPasotti (traefik?)

**Comment by simskij** [comment]
> @simskij it looks like we may need to coordinate with your team on updating your charms with the next release of ops. Do you have any thoughts on the best way to do so?

Sorry for the late reply; this seems to have gotten buried in my notification center. A list of changes we need to do would be a great start. A good starting point would be to bring it up in https://chat.charmhub.io/charmhub/channels/observability

**Comment by benhoyt** [comment]
Just to summarize my investigation from today on the `canonical/postgresql-operator` charm failure, ["Remote unit name invalid"](https://github.com/canonical/operator/actions/runs/3433841001/jobs/5724582821):

* this check was introduced as a ValueError exception [here](https://github.com/canonical/operator/pull/795/files#diff-37e8d80748bba21bb08c982f17b7879059bacc8d413b59da998a896fca18be33R713)
* then it was (properly, I think) downgraded to a warning [here](https://github.com/canonical/operator/pull/822/files#diff-37e8d80748bba21bb08c982f17b7879059bacc8d413b59da998a896fca18be33R714)
* then (presumably accidentally) reverted back to an exception when typing was added to `ops/testing.py` [here](https://github.com/canonical/operator/pull/828/files#diff-37e8d80748bba21bb08c982f17b7879059bacc8d413b59da998a896fca18be33)

I'll submit a separate PR to revert this back to a warning to avoid breaking charm tests. We should also submit a PR to the `canonical/postgresql-operator` charm to fix the name so there's not a warning.

As for the ["Function overloaded function could always be true"](https://github.com/canonical/operator/actions/runs/3433841004/jobs/5724582959) failure, I think this is a typing issue with the `StoredState` type annotations, but haven't got to the bottom of that yet.

**Comment by benhoyt** [comment]
@jnsgruk What do you think about adding these 4 data platform db charms to our ops tests? They seem to pass right now anyway. Are they relatively stable?

**Comment by jnsgruk** [comment]
Yeh I think this is a good thing. The CI for these charms shouldn't allow merges to `main` without passing unit tests, so they should be pretty stable for these purposes.

**Review by jnsgruk — APPROVED** [review]

**Pull request merged**
