### PR TITLE
begin_with_initial_hooks now sets post install status correctly

### LINKED ISSUE #726: `begin_with_initial_hooks` should end up in UnknownStatus if charm did not `set-status` during startup
It seems that at the moment, `begin_with_initial_hooks` would end up in MaintenanceStatus if the charm didn't `set-status`, 

https://github.com/canonical/operator/blob/45e1e5a9e4e99492d09423436b8378f955c4f0a3/ops/testing.py#L1034

unlike juju, which ends up in UnknownStatus. This behavior is also documented in an ops docstring:

https://github.com/canonical/operator/blob/45e1e5a9e4e99492d09423436b8378f955c4f0a3/ops/model.py#L885-L891

If you deploy a blank charm,

```shell
mkdir blank
charmcraft init -p blank
cd blank
# comment out: self.unit.status = ActiveStatus()
charmcraft pack
juju deploy ./blank_ubuntu-20.04-amd64.charm --resource httpbin-image=kennethreitz/httpbin
```

Then it indeed goes into UnknownStatus.

### PR DESCRIPTION
**Pull request by pengale**
Change the behavior of the begin_with_initial_hooks test fixture to
better reflect the behavior of production Juju.

Specifically, after the fixture runs the install hook, we check unit
status. If the status is "maintenance" with an empty message, we
assume that the install hook did not set a status, and set the unit's
status to Unknown.

Resolves #726

### CODE REVIEW

**Comment by rwcarlsen** [comment]
@sed-i was saying that maybe it doesn't go into unknown until after the first config-changed is fired (and the charm never set any status)...

**Comment by pengale** [comment]
> @sed-i was saying that maybe it doesn't go into unknown until after the first config-changed is fired (and the charm never set any status)...

Yep! I need to set aside five minutes to move the code around, and then push an update.

**Comment by pengale** [comment]
> > @sed-i was saying that maybe it doesn't go into unknown until after the first config-changed is fired (and the charm never set any status)...
> 
> Yep! I need to set aside five minutes to move the code around, and then push an update.

And done!

**Review by jnsgruk — APPROVED** [review]
LGTM, thanks @pengale

**Comment by sed-i** [comment]
I have a blank charm (no config.yaml) which sets its status on pebble ready (which is the only method in the charm).

```python
    def _on_workload_pebble_ready(self, event):
        self.unit.status = ActiveStatus()
```

In that case, unit tests fail:
`AssertionError: UnknownStatus() != ActiveStatus('')`

The tests pass if I
`self.framework.observe(self.on.config_changed, self._on_workload_pebble_ready)`

But that is awkward for a config-less charm.

When deployed with juju (with or without registering config_changed), the status is `active/idle`. Seems like juju's logic for the status is more sophisticated than currently implemented in harness.

**Comment by pengale** [comment]
> When deployed with juju (with or without registering config_changed), the status is active/idle. Seems like juju's logic for the status is more sophisticated than currently implemented in harness.

Hrm. The tests created by `charmcraft init` don't call `begin_with_initial_hooks`, but they do call `{{workload-name}}_pebble_ready`, which will set the status.

The `charmcraft init` template does namespace its `pebble_ready` handler, and the tests call the namespaced handler. Did you update the name of the handler in `charm.py`? If so, did you change the name of the handler that the tests call to match?

**Comment by sed-i** [comment]
I used the [operator-template](https://github.com/canonical/operator-template/).
Not sure what you mean though. Do you mind taking a look at the code?
- test: https://github.com/sed-i/flog-k8s-operator/blob/main/tests/unit/test_charm.py
- failure: https://github.com/sed-i/flog-k8s-operator/runs/5686244029?check_suite_focus=true#step:4:26

**Comment by rwcarlsen** [comment]
begin_with_initial_hooks doesn't generate a pebble_ready event.

**Comment by sed-i** [comment]
:scream: I don't think any of the tests I ever wrote issue a pebble ready event on their own. :scream:

**Comment by sed-i** [comment]
Might be worthwhile to be more explicit about it in the begin_with_initial_hooks docstring `Example::` section.

**Pull request merged**
