### PR TITLE
chore: upgrade ruff to v0.7.0

### PR DESCRIPTION
**Pull request by IronCore864**
Currently, we are using ruff 0.4.5 but recently 0.7.0 was released, this PR upgrades ruff to 0.7.0 for both formatting and linting.

Closes https://github.com/canonical/operator/issues/1335.

### CODE REVIEW

**Review by benhoyt — COMMENTED** [review]
Looks good overall, thanks. Regarding [this issue](https://github.com/astral-sh/ruff/issues/7313) / SIM115, unless I'm missing something, it looks like it's intentionally flagging those now, so I don't think we should have TODO comments on these, right?

We should just keep the `noqa: SIM115` comments as this will be always on now.

**Comment by dimaqq** [comment]
> Looks good overall, thanks. Regarding [this issue](https://github.com/astral-sh/ruff/issues/7313) / SIM115, unless I'm missing something, it looks like it's intentionally flagging those now, so I don't think we should have TODO comments on these, right?
> 
> We should just keep the `noqa: SIM115` comments as this will be always on now.

I've opened https://github.com/canonical/operator/issues/1440 to fix this.
Fine to keep `# noqa: ...` or `# noqa: ...  # https://github.com/canonical/operator/issues/1440` until then.

**Review by dimaqq — CHANGES_REQUESTED** [review]
I wonder why so few changes are required.

Perhaps it's because Tony already took care of a lot of stuff during the Scenario merge.

Or maybe it's an invitation for us re-enable some of the ignored codes?

Please check if there's some low-hanging fruit. 

For example, it seems that C408 no longer needs to be ignored.

**Comment by tonyandrewmeyer** [comment]
> I wonder why so few changes are required.

I suspect that using `--preview` helps, because that lets us be a bit ahead of rules hitting stable. We also generally write well crafted and formatted code, so there's less for the linter/formatter to find problems with. Looking over the new rules and rule changes, there's a bunch that aren't related to anything we do (e.g. async stuff).

> Or maybe it's an invitation for us re-enable some of the ignored codes?

For background: most of the ones that are in pyproject.toml as ignored (in the first section) we want to keep ignoring. There are a few that have comments indicating that we'd want to consider enabling them in the future. I think mostly those will be better as separate PRs, though. If there are `noqa` pragmas in the code then those would be great to remove if that becomes feasible.

It would be good to check if there are any new rules/sets that we should consider enabling, either here or separately.

**Comment by IronCore864** [comment]
Per the discussion above, we are keeping `noqa` for SIM115.

Per discussion in today's standup, we agreed to merge this PR first and then handle the refactor (try to remove rules that are not hitting anything or only affect a few places) in a separate PR.

**Review by dimaqq — APPROVED** [review]

**Review by benhoyt — APPROVED** [review]

**Pull request merged**
