### PR TITLE
Fix model types

### PR DESCRIPTION
**Pull request by PietroPasotti**
Added direct pebble imports to circumvent:

Fixes https://github.com/canonical/operator/issues/798

## Checklist

 - [x] Have any types changed? If so, have the type annotations been updated?

## QA steps

Verified that importing ops in xenial with py 3.5.3 works (while from the main branch it gives the expected error)
#800 should pass 

## Changelog

- Fixed issue with imports on py 3.5.x (xenial)

### CODE REVIEW

**Review by rwcarlsen — APPROVED** [review]
Let's get a confirmation from @tlm that this works before merging.

**Comment by rwcarlsen** [comment]
@pengale or @jnsgruk - could we get a second review/approval on this?  I'd like to get it in so we can include it in the release.

**Review by jnsgruk — APPROVED** [review]
LGTM

**Comment by tlm** [comment]
Hey guys,

Can confirm this fixes it. Thanks for the effort much appreciated.

tlm

**Pull request merged**
