### PR TITLE
fix: correct the signature of .events()

### LINKED ISSUE #1341: `Framework.ObjectEvents.events` has wrong signature
The signature of the `.events()` method is:

```python
    def events(self) -> Dict[str, EventSource]:
        """Return a mapping of event_kinds to bound_events for [...]
```

so what is it, EventSource or bound_events?
Turns out in practice it is a mapping of str to BoundEvent (docstring is correct, type annotation is wrong).

image

### PR DESCRIPTION
**Pull request by PietroPasotti**
Fixes #1341

### CODE REVIEW

**Comment by tonyandrewmeyer** [comment]
Thanks! Curious that pyright doesn't complain about this.

**Comment by PietroPasotti** [comment]
I think it didn't because all attributes that were accessed were coincidentally common between the two types :)
they both talked like ducks

**Review by tonyandrewmeyer — APPROVED** [review]
LGTM, thanks!

The main case seems very straightforward - the code is clearly wanting the bound event - it's even asserting on it. The error message probably works either way, but I'm +0 on this adjustment.

The framework one should indeed be working with bound events - the class has the source, the instance has the bound event.

**Review by benhoyt — APPROVED** [review]
Thanks!

**Pull request merged**
