### PR TITLE
Interface pgsql

### PR DESCRIPTION
**Pull request by jameinel**
This introduces `ops.lib.pgsql.client.PostgreSQLClient`. Which supports basic interaction with the `postgresql` charm.
Hopefully things are well documented and straightforward. Now is the time to start coloring our bike and how we want the bikes to fit inside.

This depends upon https://github.com/canonical/operator/pull/196

### CODE REVIEW

**Comment by stub42** [comment]
I've also got https://git.launchpad.net/~stub/interface-pgsql/+git/operator/tree/ which I have been getting ready

**Comment by chipaca** [comment]
@stub42 this interface is prominent enough that i'd rather have it in the framework itself, but you are the domain expert here (right?) so it would be silly for us to do this while you are doing your own, as yours will probably better in the long run even if you haven't been able to give it a lot of time yet. Can we pull your work in, and work on it here, together?

@jameinel am i making sense here :-)

**Comment by stub42** [comment]
On Thu, 2 Apr 2020 at 09:33, John R. Lenton <notifications@github.com>
wrote:

> @stub42 <https://github.com/stub42> this interface is prominent enough
> that i'd rather have it in the framework itself, but you are the domain
> expert here (right?) so it would be silly for us to do this while you are
> doing your own, as yours will probably better in the long run even if you
> haven't been able to give it a lot of time yet. Can we pull your work in,
> and work on it here, together?
>
> @jameinel <https://github.com/jameinel> am i making sense here :-)
>

I'm not fussed what namespace this ends up under or where the source repo
is. I have the branch sitting in my personal namespace at the moment
because I don't know how we want to brand it or what license to stick on
it. Or if the overall design is what we expect. It will need to be evolved
in tandem with the PostgreSQL charm, as it makes use of newer Juju features
and drops compatibility with old releases over time. In particular, my
interface is attempting to make the switch to application relation data
(avoiding the usual required consensus from clients), although the
disgusting hack you will find in the source makes it obvious there are
still rough edges to be smoothed off.

I'd be wary of including the interfaces in the main repo; the CI system
will become a nightmare, as we will want integration tests against stable
and edge cs:postgresql, and that will be magnified the more interfaces that
end up in the main repo. Perhaps a submodule that is updated from a stable
branch in a separate repo.

**Comment by jameinel** [comment]
My goal was to pick and interface that was important, and use it to drive our design and our recommendations. (It is also one of the more interesting interfaces as it has various hand-shaking between the two sides, rather than just consuming a data bag.)

That said, I'm *more* than happy to defer to Stub maintaining the interface. IMO, interfaces should be maintained by the maintainer of the Charm that implements it.
Trying to figure out what distributed maintenance of shared artifacts looks like is certainly going to be a challenge.

**Comment by timClicks** [comment]
> That said, I'm more than happy to defer to Stub maintaining the interface. IMO, interfaces should be maintained by the maintainer of the Charm that implements it.

This concerns philosophy me. Interfaces are independent of charms by design. There are multiple charms potentially providing `pgsql`. Moreover, the Juju community has multiple charming frameworks and this module won't be importable by them.

Interfaces are shared technical infrastructure and should be treated as such. Without that mentality, there's little emphasis on communication.

**Comment by niemeyer** [comment]
I'm closing this for the time being so we don't leave it hanging.

@jameinel Can you please establish some closer contact with @stub42 and do an early pass on his interface and charm code, providing feedback that portrays our current agreements?

**Pull request closed without merging**
