### PR TITLE
Final patch for 1.5.1 release

### PR DESCRIPTION
**Pull request by rwcarlsen**
Okay.  I turned on branch-protection rules for any `*-maintenance` branches.  I saved the last cherry-pick for 1.5.1 to put in this PR in order to test/check that CI works right for this maintenance branch.  I assume that the publishing checks and actions will work the same for releases no matter which branch they come from.

### CODE REVIEW

**Comment by rwcarlsen** [comment]
Notably - there were some conflicts I had to resolve (since this PR was oritinally built on some stuff that was excluded form this patch release).  So @PietroPasotti - if you could confirm that the xenial issues are still fixed here - that would be great.

**Review by PietroPasotti — APPROVED** [review]
Checked that the xenial bug is fixed.
LGTM

**Comment by pengale** [comment]
Can we add the smoke test to the 1.5.1 branch? That would make it a lost easier to do things like verify that xenial is working. :-)

**Comment by rwcarlsen** [comment]
@pengale - done.

**Review by pengale — APPROVED** [review]
Thx for including the smoke test stuffs! I am +1 on this.

**Pull request merged**
