### PR TITLE
use yaml instead of json for pod-spec-set call

### PR DESCRIPTION
**Pull request by chipaca**
fixes: #293

### CODE REVIEW

**Comment by chipaca** [comment]
> We should test that this works on a K8s charm

@darkalia was hoping to get back to me with that sometime tomorrow (if I got that right :slightly_smiling_face: )

**Comment by jameinel** [comment]
On the plus side, reactive already is using yaml for the interaction:
https://github.com/juju-solutions/layer-caas-base/blob/master/lib/charms/layer/caas_base.py

Interestingly they don't make use of the multiple arguments but just strictly concatenate the two and pass it on stdin.
That feels a bit dirty as content goes, but I can see an advantage of not having temp files.

**Comment by jameinel** [comment]
Actually rather surprising as yaml.dump() doesn't create a document boundary (`---\n` in yaml), so it means it all comes through as a single document.

**Comment by chipaca** [comment]
> Actually rather surprising as yaml.dump() doesn't create a document boundary (`---\n` in yaml), so it means it all comes through as a single document.

suspect it's used with filenames, in which case it would do the right thing except for the space. The usage where both things are not strings makes no sense to me.

**Comment by chipaca** [comment]
so, looking at the code, pod-spec-set just munges the two things together anyway. Which is why it doesn't work with json.

I can't even.

**Comment by darkalia** [comment]
I tested and confirmed this works with a k8s charm.

I updated my k8s charm and tested with and without this fix : https://pastebin.ubuntu.com/p/VPpRGpr9D8/
My WIP branch with the change is https://code.launchpad.net/~ballot/charm-k8s-mm-pd-bot/+git/charm-k8s-mm-pd-bot/+merge/389156
:+1:

**Pull request merged**
