### PR TITLE
return charm and event instances from ops.main.main

### PR DESCRIPTION
**Pull request by PietroPasotti**
When using ops.main from a python script, it is often useful to get a hold of the charm instance created by the framework and the instance of the event fired on it.

Right now, if I wanted to call ops.main.main() from a script and obtain the charm instance, I'd have to either go and mess with the AST to add the return statement or print to a specific line (as in https://github.com/PietroPasotti/jhack/blob/dd516d52b45ab8cd7583b2d0b6919fe7df5d3296/jhack/utils/event_recorder/runtime.py#L140 ) or copy-paste the contents of `main` with the maintenance burden that implies if `ops.main` were to change in the future.

This PR adds a few return statements to ops.main and framework to avoid these workarounds.

## Checklist
 - [x] Have any types changed? If so, have the type annotations been updated?

## QA steps

Added an unittest to check the new behaviour.

## Documentation changes

Nothing that the average user will need to worry about.

## Changelog
- `ops.main` return type is now `Tuple[CharmBase, EventBase]`

### CODE REVIEW

**Comment by jameinel** [comment]
I'm not opposed to the change, but I'd be very surprised to run ops.main.main() from testing, because there is a *lot* of assumptions in that code about being the actual single process that is running (messing with env vars, etc). It feels more like we should refactor out the helpful bits and then drive that from main, rather than exposing return from main itself.

**Comment by benhoyt** [comment]
If we included this change, we'd have to rename jhack to jnothackyanymore, and we can't have that! ;-)

Seriously though, I think we should step back and see how `ops` can better support the use case(s) that jhack needs in a more holistic way. I've scheduled some time to chat with @PietroPasotti tomorrow morning.

**Comment by benhoyt** [comment]
Just adding a link: the context here is @PietroPasotti's new "scene-based" testing idea from here: https://github.com/PietroPasotti/ops-scenario ... He's intercepting the hook tool calls and mocking the return values. This ties in with his `jhack replay` tool as well.

**Comment by benhoyt** [comment]
Realistically we won't be merging this in this form. It's fine for jhack to "hack", and also ops is very stable (changes very slowly), so the workaround you have today shouldn't have to change much if at all. And if we come up with a better way to structure this, happy to discuss.

**Pull request closed without merging**
