### PR TITLE
Allow Harness.get_relation_data to accept instances

### PR DESCRIPTION
**Pull request by johnsca**
It's tripped me up a few times that you have to pass in the name of the app or unit rather than the instance itself that you use everywhere else, so this allows get_relation_data to handle either.

### CODE REVIEW

**Comment by johnsca** [comment]
There are several other methods where this would be nice as well, so if I have time I might go through and update them all.  If the general idea is ok, feel free to block this on making them all consistent.

**Review by kwmonroe — COMMENTED** [review]
+1 on the general idea

**Review by jameinel — COMMENTED** [review]
I don't have a hard problem with it taking an application, but I did find the tests easier to read when it was explicit names rather than objects. I'd be curious to see what your tests look like, and whether they are easier or harder to understand using object names.

**Comment by johnsca** [comment]
@jameinel I think my main issue was that I was used to using the object instances themselves in the charm and interface code to access the data, so that's just what I naturally did in the tests as well.  Then my tests failed with confusing results because instead of rejecting the instances, it just treated them as if there was no data when I expected there to be.

Also, I do find typing strings all of the place more prone to typos and mistakes that, again, will lead to confusing failures rather than being caught by the linter or interpreter. That can be mitigated by assigning the strings to variables, but then it's not really any different than using the instances directly.

One downside of using instances is that it is harder to reference a remote unit or application, since you don't have an easy way to get the instance, so in that case, just being able to say `"my-charm/0"` and `"my-charm/1"` is easier.

**Comment by johnsca** [comment]
FWIW, I'm using helpers which do something akin to this in [the loadbalancer-interface functional tests](https://github.com/juju-solutions/loadbalancer-interface/blob/main/tests/functional/test_interface.py). That test should probably be refactored into steps to help with readability, but maybe it can at least give an indication as to why it might be easier to work with model objects directly rather than just names.

**Comment by benhoyt** [comment]
@jameinel I'm on the fence about this (though maybe that's my recent statically-typed Go experience speaking).

However, one thing that comes to mind is: we already use many type annotations in the project. If we finish that and get `mypy` running on the project, would this be better solved by using mypy's type checking? That way you'd catch "oops, I should be using `app.name` here" errors at build/type check time rather than runtime.

**Comment by Vultaire** [comment]
In my opinion:
* I'm +1 for being more forgiving about input here.  While I agree that strings look simpler, I also agree that typos are more likely an issue.  While there's other ways to address this, as the framework does use Unit/Application objects elsewhere, to me it seems reasonable to accept such here.
* This seems like an issue specifically with the relation-related harness functions, i.e. add_relation, add_relation_unit, get_relation_data and update_relation_data.  And for most of these, it seems a fairly simple change with no real API changes aside from making the type annotations looser.
* There is one small backwards compatibility concern re: add_relation_unit, as it uses "remote_unit_name", and with this rework it'd make better sense for that to be "remote_unit".  That's break tests which pass in by keyword argument if we rename that, although perhaps that's a fairly minor concern.

**Review by petevg — APPROVED** [review]
This PR needs a rebase, but I am +1 to the principle, and the general implementation.

Being loosey goosey with the types of args is perhaps a little scary. But it is also in keeping with some of the design principals of Python. And @johnsca is being careful here with the types that the method does accept.

This is the sort of design that makes it more likely that a charm author's intuition will be correct, which makes for happier charm authors, and less pressure on the the docs to guide folks who are writing charms.

**Review by niemeyer — APPROVED** [review]
Idea looks good, thanks. We already do that sort of logic inside the model itself, don't we? So it does make sense that the Harness would also accept it.

**Comment by jnsgruk** [comment]
Oops, that merge commit broke the tests. I did some work on this locally to rectify but cannot push to the branch, [this patch](https://gist.github.com/jnsgruk/ba2a64a1b642c45c6cec5a237c5057f5) brings this PR up to date, and makes the test suite pass etc. taking into account changes that have happened since!

**Pull request merged**
