### PR TITLE
Log event deferral and reëmission.

### PR DESCRIPTION
**Pull request by chipaca**
fixes: #410

### CODE REVIEW

**Review by justinmclark — APPROVED** [review]
LGTM

**Review by johnsca — APPROVED** [review]

**Review by facundobatista — APPROVED** [review]
Awesome, thanks!

**Comment by chipaca** [comment]
Waiting for confirmation on the issue before merging this

**Comment by chipaca** [comment]
After chatting with @camille-rodriguez we agreed to merge this and she will reopen the issue is it is not fixed by this (in my testing it looks like it should)

**Pull request merged**
