### PR TITLE
fix: Handle empty `config.yaml` files in Harness

### LINKED ISSUE #617: Test Harness fails to instantiate if config.yaml exists and has no data
`Harness(MetacontrollerOperatorCharm)` will fail with:
```
    def _load_config_defaults(self, charm_config):
        """Load default values from config.yaml.
    
        Handle the case where a user doesn't supply explicit config snippets.
        """
        filename = inspect.getfile(self._charm_cls)
        charm_dir = pathlib.Path(filename).parents[1]
    
        if charm_config is None:
            config_path = charm_dir / 'config.yaml'
            if config_path.is_file():
                charm_config = config_path.read_text()
                self._charm_dir = charm_dir
            else:
                # The simplest of config that the framework can support
                charm_config = '{}'
        elif isinstance(charm_config, str):
            charm_config = dedent(charm_config)
        charm_config = yaml.safe_load(charm_config)
>       charm_config = charm_config.get('options', {})
E       AttributeError: 'NoneType' object has no attribute 'get'
```
if `config.yaml` exists but is empty (eg: has no content or only comments).  This is because `yaml.safe_load("#only comments or empty string")` returns None

(edited - original message accidentally had `charm.yaml` when the problem is with `config.yaml`)

### PR DESCRIPTION
**Pull request by ca-scribner**
fixes #617.  Alternatively, this situation could instead raise an informative error message about how empty `config.yaml`s are not allowed, if that is better.

### CODE REVIEW

**Comment by jnsgruk** [comment]
So I'm guessing this should be about `config.yaml`?

If so, I think trying to include an *empty* `config.yaml` is indeed an error. I just did a quick test, and Juju will refuse to deploy a charm with an empty `config.yaml`. You can certainly omit the `config.yaml` file completely, but if it is present it must have the `options:` key at the top level afaict.

(Interestingly, `charmcraft` will pack a charm with an empty `config.yaml`, so I might raise an issue there, too)

**Comment by ca-scribner** [comment]
oh yeah good catch, I meant to say `config.yaml`.  thanks!

**Review by petevg — CHANGES_REQUESTED** [review]
Juju will fail to deploy a charm with a blank config.yaml; it wouldn't be a good idea to allow the test harness to behave differently.

I would be on board with wrapping and raising a more informative error here instead.

**Comment by ca-scribner** [comment]
Agreed that test harness and Juju should be aligned.  But from a UX perspective, does it make sense that Juju succeeds if you omit the `config.yaml` but fails if you include an empty `config.yaml`?  Having `null` and empty behave differently here feels odd and I wonder if improving the error message here fixes the wrong problem

**Comment by rbarry82** [comment]
I do think it fixes the wrong problem. We could also stub it out in charmcraft, but it's an ecosystem problem:

* Charmcraft should now allow empty `config.yaml` if Juju can't parse it. This is a first-line check, until...
* Juju should handle empty `config.yaml` more gracefully, even if having it at all is an antipattern. If anything, Juju should simply not repack this file for deployment if it's empty, since it's not useful
* Operator framework should follow whatever decision the previous two reach. If Juju accepts and passes on an empty file, we can add handling for it

Considering that, for now, Juju will refuse to deploy it in the first place, OF handling of a null case is probably unnecessary, and having this handling at all leaves a handoff problem where your charm will build and OF will handle it but Juju will throw its hands up.

**Comment by jnsgruk** [comment]
Hi @ca-scribner! I spoke earlier with @niemeyer about this. I think the sensible thing to do here for now is that the Harness should match the behaviour of Juju as much as possible. Could you possibly make some changes to this patch that make the Harness raise an exception if there is an empty `config.yaml` present? That will at least bring the Harness in line with Juju.

**Comment by jameinel** [comment]
So the actual code in Juju was written back in 2014, so the specific purpose is probably slightly lost to time. (in github.com/juju/charm:  
```
Author: Roger Peppe <rogpeppe@gmail.com>
Date:   Mon Nov 17 17:37:47 2014 +0000

    disallow config.yaml with no options entry
```
My interpretation is:

a common pitfall for writing config.yaml is to just put the values in there. eg:
```
$ cat config.yaml
s:
  type: string
  default: "abcd"
```

vs what juju can actually parse:
```
$ cat config.yaml
options:
    s:
        type: string
        default: "abcd"
```

Because of how we're doing non-strict yaml parsing, the struct we're using can't tell the difference between an empty file and a file without an 'options:' section.
We could fix that parser to give better feedback, but it won't change all of the existing released juju's to actually support it. (a charm with an empty config.yaml will fail for some juju's that try to deploy it.)

I do think it makes sense to update Juju to treat an empty config.yaml as though it doesn't exist, as long as we do properly fail when someone has it incorrectly structured.
But charmcraft and Harness should probably at a minimum warn, since all released versions (as of today) of Juju won't support it.

**Comment by ca-scribner** [comment]
Sorry I let this fall out of vision.  I'll address it shortly.  And thanks
for the review/suggestions!

**Comment by petevg** [comment]
This PR has been stalled out for a while, and I am going to go ahead and close it.

**Pull request closed without merging**
