### PR TITLE
docs: update read the docs site to latest Canonical styling

### PR DESCRIPTION
**Pull request by IronCore864**
Update read the docs/sphinx settings to use latest Canonical style.

Closes https://github.com/canonical/operator/issues/1158.

### CODE REVIEW

**Comment by jameinel** [comment]
Thank you for generating the preview.
For the most part, I think it looks better. Having it distinguish the code blocks from prose is more readable to me.

2 small complaints, and I'm not sure if it has anything for @IronCore864 to do.
image
image

In light mode, it is using white underlines for Type names as well as Blue text. I think they are hyperlinks, but shouldn't that be Blue text with Blue underlines?

Conversely in Dark mode, we end up with light (white?) text on light grey background. I would have expected it to go to a "dark grey" background to more closely match the 'subtle highlight' that we have in the light mode.

**Comment by IronCore864** [comment]
> Thank you for generating the preview. For the most part, I think it looks better. Having it distinguish the code blocks from prose is more readable to me.
> 
> 2 small complaints, and I'm not sure if it has anything for @IronCore864 to do. image image
> 
> In light mode, it is using white underlines for Type names as well as Blue text. I think they are hyperlinks, but shouldn't that be Blue text with Blue underlines?
> 
> Conversely in Dark mode, we end up with light (white?) text on light grey background. I would have expected it to go to a "dark grey" background to more closely match the 'subtle highlight' that we have in the light mode.

Maybe it has something todo with previously done customizations; I'll open up a new PR to start from scratch with the starter kit and do some tweaks from there, then do a comparison to see which way to go.

**Comment by IronCore864** [comment]
I have created [another PR here](https://github.com/canonical/operator/pull/1162).

The difference is, in this PR, I merged the Canonical starter pack with what we've got so as not to lose anything we customized.

In the new PR, I started from scratch with the Canonical starter pack (and did some hacking, like autodoc, and fixing the two issues John mentioned).

Please go to the new PR, do a preview, and compare which you like.

@jameinel @benhoyt @tonyandrewmeyer

**Comment by IronCore864** [comment]
Closing this PR because the other one here https://github.com/canonical/operator/pull/1162 looks more like what we want.

**Pull request closed without merging**
