### PR TITLE
add symmetrical teardown sequence simulator in Harness

### PR DESCRIPTION
**Pull request by PietroPasotti**
At the moment the harness exposes two ways to get started with testing:
- begin() -> instantiate the charm 
- begin_with_initial_hooks() -> begin(), plus simulate the setup phase sequence (see https://discourse.charmhub.io/t/a-charms-life/5938)

This PR:
- `begin_with_initial_hooks` is deprecated and renamed to `simulate_setup_sequence()` which does by default calls begin().
- added `simulate_teardown_sequence()` which does the symmetric of `simulate_setup_sequence()` and 1) detaches all storage 2) breaks all relations 3) fires stop and remove.

This is a step towards higher-level sequence-based testing methods in the harness.

**TODO:** add tests for the new method, uniformly replace the renamed function

## Documentation changes

The docs will need to be updated with the deprecation notice and the new method.

## Changelog
- Rename and deprecate `testing.Harness.begin_with_initial_hooks --> testing.Harness.simulate_setup_sequence`
- Added `testing.Harness.simulate_teardown_sequence`

### CODE REVIEW

**Review by pengale — COMMENTED** [review]
TODOs still need to be TODONE, but I like this approach.

The relative simplicity of the teardown routine says good things about the harness, I think. It's possible to do a lot, with fairly minimal code.

**Comment by rwcarlsen** [comment]
I'd prefer we build up a set/group of sequence functions (or something like that) that users can grab from rather than add more sequence funcs to the harness.  There are some things about building such a function external to the harness that are tricky/awkward - those are the things that I think we need to improve in the framework (i.e. retrieving lists of relevant objects/ids to loop over/shuffle, etc.).  Then we can provide standard helpers like this:

```python
def charm_teardown(harness):
        storages = ...
        random.shuffle(storages)
        # fire all storage-detaching events
        for storage_id in storages
                harness.detach_storage(storage_id)

        relations = ...
        random.shuffle(relations)
        for rel_id, rel_name in relations:
            ...
            
def event_fuzzer(harness, n=42):
        ...
```

To do this right, we'd definitely want to figure out a way to reset the charm instance for every hook call.

**Comment by PietroPasotti** [comment]
> I'd prefer we build up a set/group of sequence functions (or something like that) that users can grab from rather than add more sequence funcs to the harness. There are some things about building such a function external to the harness that are tricky/awkward - those are the things that I think we need to improve in the framework (i.e. retrieving lists of relevant objects/ids to loop over/shuffle, etc.). Then we can provide standard helpers like this:
> 
> ```python
> def charm_teardown(harness):
>         storages = ...
>         random.shuffle(storages)
>         # fire all storage-detaching events
>         for storage_id in storages
>                 harness.detach_storage(storage_id)
> 
>         relations = ...
>         random.shuffle(relations)
>         for rel_id, rel_name in relations:
>             ...
>             
> def event_fuzzer(harness, n=42):
>         ...
> ```
> 
> To do this right, we'd definitely want to figure out a way to reset the charm instance for every hook call.

While I agree with what you said, I think that's a major refactor/change in Harness design that should be tackled in a separate PR and requires some further speccing/design work.

The scope of this PR is intentionally narrower than that. I propose that we merge this PR and then agree to stop adding 'fire this event sequence' methods to the harness until we have a more general approach. I still think this one deserves to be there to complete the current Harness without changing its design philosophy.

**Comment by pengale** [comment]
Closing this out for now. We have a request to do a bit more design work before pushing this change into core. We can re-open/recreate later when that work is complete.

**Pull request closed without merging**
