### PR TITLE
docs: clarify that SecretNotFound may be raised for permission errors

### PR DESCRIPTION
**Pull request by tonyandrewmeyer**
As noticed in #1229, `get_secret()` may raise `SecretNotFoundError` if the secret does exist but the caller does not have permission to view it, so make this explicit in the documentation.

### CODE REVIEW

**Review by benhoyt — COMMENTED** [review]
But isn't the point of #1229 that Ops will currently raise `ModelError` for permission/grant errors?

**Comment by benhoyt** [comment]
Oh, I see -- we're closing #1229, and this PR goes on the assumption that the Juju bug will be fixed.

**Comment by tonyandrewmeyer** [comment]
> Oh, I see -- we're closing #1229, and this PR goes on the assumption that the Juju bug will be fixed.

Yes - my assumption is that since @wallyworld agrees that Juju should be consistent that the Juju bug will get fixed.

But also: this is *already* the case for everything other than user secrets. If we wanted it to reflect the current behaviour, then it should have this change and also a new "raises" item of "ModelError: when the secret is a user secret and the charm does not have permission to view it". My preference would be to not add that now on the assumption that it won't be true soon (for some value of "soon").

**Review by benhoyt — APPROVED** [review]
Makes sense to me -- thanks.

**Pull request merged**
