### PR TITLE
ci: make Pyright report unnecessary type ignore comments

### PR DESCRIPTION
**Pull request by dimaqq**
Parent: https://warthogs.atlassian.net/browse/CHARMTECH-232

Covered in the parent epic:

- charmcraft analyse will validate that charm Python entrypoint calls ops.main
- it is static type checker’s job to ensure correct arguments to ops.main
- today, many charms do and have to do ops.main(ThisCharm)  # type: ignore 
- thus, type hints need to be improved so that typpe: ignore can be dropped

 

Plan in this story:

- upgrade pyright (not sure if strictly necessary, #1332)
- enabled pyright setting reportUnnecessaryTypeIgnoreComment
- include code that calls ops.main(SomeCharm) in every which legal way in ops tests somewhere
   - pyright validates the positive case, that ops.main can be called with a charm class
- include code that calls ops.main() without a charm class
   - pyright now validates that such invocation is detected as an error
   - thus, this invocation is annotated with # type: ignore or similar
   - with the setting above, pyright also enforce that the annotation is actually needed

Ref: "How to write negative type tests?" https://github.com/microsoft/pyright/discussions/8803

Part 2, based on #1332 

MyPy checks, pinned mypy:
- [x] `nginx-ingress-integrator-operator` mypy 1.6.1 OK
- [x] `sdcore-webui-operator` mypy 1.11.1 OK

Super-tox, running on host (macos)
- 58 charms pass against canonical/operator@main
- 58 charms pass against dimaqq/aoperator@pyright-reportUnnecessaryTypeIgnoreComment

### CODE REVIEW

**Review by benhoyt — COMMENTED** [review]
Similar to my comment on #1332, let's just ensure that removing these doesn't mess with charms that use MyPy for type checking.

**Comment by dimaqq** [comment]
I've updated the description.

**Review by tonyandrewmeyer — APPROVED** [review]

**Comment by dimaqq** [comment]
re failing o11y tests, it's an upstream issue, a test dep is not pinned:
https://github.com/canonical/prometheus-k8s-operator/pull/638
https://github.com/canonical/alertmanager-k8s-operator/pull/286

**Review by benhoyt — APPROVED** [review]
Nice cleanup, thanks!

**Pull request merged**
