### PR TITLE
Allow for missing fields in network-get response

### PR DESCRIPTION
**Pull request by johnsca**
There are some cases where network-get may return less information than is currently expected. This mainly seems to happen in K8s charms, since not all of the info may be available yet. This makes the model more tolerant to missing information.

### CODE REVIEW

**Comment by chipaca** [comment]
Thank you for this! I think we need to split your libyaml extension test fix to a separate PR. Could you do that easily? Otherwise I will.

**Comment by johnsca** [comment]
Yep, will do.  I included it because it was blocking my testing but it definitely should be a separate PR.

**Comment by johnsca** [comment]
TBH, I didn't notice that, but it seems like it would be better for the tests to handle it gracefully.  Split that change off to #420

**Review by chipaca — APPROVED** [review]
thank you.

**Review by justinmclark — APPROVED** [review]
+1

**Pull request merged**
