### PR TITLE
Minor documentation changes

### PR DESCRIPTION
**Pull request by tinvaan**
Simply updates a couple of outdated hrefs in HACKING.md.

### CODE REVIEW

**Review by benhoyt — APPROVED** [review]
Thanks!

The `go install` path was definitely broken (probably my mistake). I'm not sure quite why the `publish.yml` path change is necessary (the current one seems to work) but a relative path definitely doesn't hurt either.

**Comment by benhoyt** [comment]
Thanks for the contribution, @tinvaan! Trivial doc fixes so merging without further review.

**Comment by tinvaan** [comment]
> Thanks!
> 
> The `go install` path was definitely broken (probably my mistake). I'm not sure quite why the `publish.yml` path change is necessary (the current one seems to work) but a relative path definitely doesn't hurt either.

Yeah it's very trivial,  but the relative path is useful when you're viewing a markdown file locally - VSCode supports markdown file previews for eg - and a relative path href ensures that the linked document is opened in the current application itself as opposed to opening a new browser tab or window.

Also makes it easier to preview and edit the opened document -- again trivial but useful.

**Comment by benhoyt** [comment]
Good points, thanks!

**Pull request merged**
