### PR TITLE
Enable PEP257 Convention Checking

### PR DESCRIPTION
**Pull request by balbirthomas**
Enable PEP257 convention checking in `test_pep257` unit test.

### CODE REVIEW

**Comment by facundobatista** [comment]
As we talked in IRC, please revert the convention and some of the blank lines, thanks!

**Comment by balbirthomas** [comment]
> As we talked in IRC, please revert the convention and some of the blank lines, thanks!

done. please check.

**Comment by benhoyt** [comment]
I think the active / imperative mood changes on normal methods add clarity, however, I'm not a fan of it on properties, which act more like variables. So my vote would be to only do this change for normal methods, not properties.

**Comment by balbirthomas** [comment]
> I think the active / imperative mood changes on normal methods add clarity, however, I'm not a fan of it on properties, which act more like variables. So my vote would be to only do this change for normal methods, not properties.

Hi @benhoyt  Thank you for taking the time to review this. You make a fair point and indeed properties need not or should not have imperative clauses. A quick look at pydocstyle manual did not show me any way to add exceptions to convention checking on a per method basis. So it seems our choice are either to reject it or accept it altogether.  Seems like pydocstyle could do with some improvement. There is an open issue on this topic [here](https://github.com/PyCQA/pydocstyle/issues/301).

However this pull request is bit of a lost cause and I only need a slight nudge to drop it. I created it in an idle moment when I noticed that `test_pep257` in `test_infra.py` was using google doc style convention rather than pep257. On switching on pep257 convention checking there were a lot more warnings issued. These were easy to fix so I did can created a pull request. However the full changeset was not acceptable so I removed some of the commits and hence the doc style is still google. 

I am not sure if it is worth spending too much effort on this. IMHO `ops`  documentation is still sorely lacking and there would be more value in improving the content of the docs themselves.

**Comment by benhoyt** [comment]
@balbirthomas I agree with you -- there are bigger fish to fry with this repo. Two that I can think of: 1) improving documentation (as you mentioned), and 2) having mypy type checks run on the project during CI. But I'll let you update or close this if you want.

**Comment by balbirthomas** [comment]
Closing as this is no longer relavent

**Comment by jameinel** [comment]
So we certainly did do a bunch of discussion about what doc style we wanted
to use. I know we looked at @param style and google and a couple of others.
Offhand I don't remember 257, but the choice of Google was explicit and we
did rewrite things to match.
Is there something that 257 provides?
I would think mypy would care less about docstrings if we are using type
annotations.

I would ask that the code base be consistent and that we don't change it
every year, but as long as sphinx renders nice docs and if there is a
concrete benefit then it is reasonable to discuss it.

John
=:->

**Comment by balbirthomas** [comment]
>  Is there something that 257 provides? 
The PEP257 convention is a bit more stringent. Perhaps too stringent (for instance insisting that property docstrings also start with imperative clauses -- though this is a reported bug on pydocstyle issue tracker).

**Pull request closed without merging**
