### PR TITLE
[Draft] Add networking data to the harness

### PR DESCRIPTION
**Pull request by pengale**
Implements network_get in the Test Model Backend.

Adds a NetworkHarness object to hold cached data and helper methods.

The NetworkHarness can auto generate data. It also contains tooling to
allow charm authors to set specific network data, and to specify which
endpoints should successfully return network data.

Questions to answer when reviewing the draft:

- The _TestModelBackend and Harness classes were getting pretty big. Do we like the way that I split NetworkHarness into its own class? Does the referencing strategy look decent?
- Does the "active endpoints" code make sense? (The idea here is to get it working, and add automagic later on, if needed.)

### CODE REVIEW

**Comment by sed-i** [comment]
What do you think about automatically generating some network info e.g. with random 10.x.x.x IPs, unless the user already set it beforehand? For example do this from `testing.container_pebble_ready`.

The idea is when I call `begin_with_initial_hooks` it will be there for me without needing to do anything. (Speaking of which, I do not see `container_pebble_ready` being emitted from `begin_with_initial_hooks`.)

**Comment by pengale** [comment]
> ~What do you think about automatically generating some network info e.g. with random 10.x.x.x IPs, unless the user already set it beforehand? For example do this from `testing.container_pebble_ready`.~ nvm you already have that! But shouldn't bind_address be None before pebble_ready?
> 
> The idea is when I call `begin_with_initial_hooks` it will be there for me without needing to do anything. (Speaking of which, I do not see `container_pebble_ready` being emitted from `begin_with_initial_hooks`.)

@jameinel I've been meaning to ping you about this. How much do you think that this test should be linked into the sort of juju state that the harness tracks, and how much should be standalone?

**Comment by pengale** [comment]
After some discussion about the comments, I think that we want to focus on the following:

1) In the future, it would be very nice to be able to define a complex network topology in the harness, to enable people to test scenarios like cross model relations, or just an Openstack cloud with several distinct networks (and networking layers!) This code should support that, rather than getting in the way.

2) The current approach of asking test authors to explicitly set the case where the network data returned is null is the correct approach. We do not want to require charm authors to drop boilerplate in all their tests, so data should generally automagically be there, with charm authors needing to call a helper in the harness to invoke a "failure" mode.

All of the above should be well documented, of course, both in code, and in our SDK docs!

**Comment by pengale** [comment]
Closing this out for now. Work is documented in the Spec doc, as well as in the branch in my fork.

**Comment by sed-i** [comment]
Another potentially useful use case is `self.harness.upgrade(new_network=...)`

**Pull request closed without merging**
