### PR TITLE
explicitly ask for a newer sphinx on rtd

### PR DESCRIPTION
**Pull request by chipaca**

### CODE REVIEW

**Comment by jameinel** [comment]
Do we want to specifically do >2 rather than =3 or something along those lines?

**Comment by jameinel** [comment]
Why does this show all of the charm.py changes. Didn't those already land on master?

**Comment by chipaca** [comment]
maybe i made a mess of things? :-(

**Comment by chipaca** [comment]
(pulling my work from the last few days back onto my new laptop had me do some gymnastics with the branches...)

**Pull request merged**
